; Common settings for ESP targes, mixin with extends = esp32_base
[esp32v6_base]
extends = esp32_base
custom_esp32_kind = esp32
platform =
  # do not renovate
  https://github.com/pioarduino/platform-espressif32/releases/download/51.03.07/platform-espressif32.zip

build_src_filter = 
  ${esp32_base.build_src_filter} -<libpax/> -<nimble/>


# Remove -DMYNEWT_VAL_BLE_HS_LOG_LVL=LOG_LEVEL_CRITICAL for low level BLE logging.
# See library directory for BLE logging possible values: .pio/libdeps/tbeam/NimBLE-Arduino/src/log_common/log_common.h
# This overrides the BLE logging default of LOG_LEVEL_INFO (1) from: .pio/libdeps/tbeam/NimBLE-Arduino/src/esp_nimble_cfg.h
build_unflags = -fno-lto
build_flags =
  ${arduino_base.build_flags}
  -flto
  -Wall
  -Wextra
  -Isrc/platform/esp32
  -std=c++11
  -DLOG_LOCAL_LEVEL=ESP_LOG_DEBUG
  -DCORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_DEBUG
  -DMYNEWT_VAL_BLE_HS_LOG_LVL=LOG_LEVEL_CRITICAL
  -DAXP_DEBUG_PORT=Serial
  #-DCONFIG_BT_NIMBLE_ENABLED
  #-DCONFIG_NIMBLE_CPP_LOG_LEVEL=2
  #-DCONFIG_BT_NIMBLE_MAX_CCCDS=20
  #-DCONFIG_BT_NIMBLE_HOST_TASK_STACK_SIZE=8192
  -DESP_OPENSSL_SUPPRESS_LEGACY_WARNING
  -DSERIAL_BUFFER_SIZE=4096
  -DLIBPAX_ARDUINO
  -DLIBPAX_WIFI
  #-DLIBPAX_BLE
  -DHAS_UDP_MULTICAST=1
  -DMESHTASTIC_EXCLUDE_BLUETOOTH
  -DHAS_BLUETOOTH=0
  -DMESHTASTIC_EXCLUDE_PAXCOUNTER
  ;-DDEBUG_HEAP

lib_deps =
  ${arduino_base.lib_deps}
  ${networking_base.lib_deps}
  ${environmental_base.lib_deps}
  ${environmental_extra.lib_deps}
  ${radiolib_base.lib_deps}
  # renovate: datasource=git-refs depName=meshtastic-esp32_https_server packageName=https://github.com/meshtastic/esp32_https_server gitBranch=master
  https://github.com/Xavierhorwood/esp32_https_server.git#6b6f7b19ea14af9340f0ad74221dd081d5809bb5
  # renovate: datasource=custom.pio depName=NimBLE-Arduino packageName=h2zero/library/NimBLE-Arduino
  h2zero/NimBLE-Arduino@^2.2.3
  # renovate: datasource=git-refs depName=libpax packageName=https://github.com/dbinfrago/libpax gitBranch=master
  https://github.com/dbinfrago/libpax/archive/3cdc0371c375676a97967547f4065607d4c53fd1.zip
  # renovate: datasource=custom.pio depName=XPowersLib packageName=lewisxhe/library/XPowersLib
  lewisxhe/XPowersLib@^0.2.9
  # renovate: datasource=git-refs depName=meshtastic-ESP32_Codec2 packageName=https://github.com/meshtastic/ESP32_Codec2 gitBranch=master
  https://github.com/meshtastic/ESP32_Codec2/archive/633326c78ac251c059ab3a8c430fcdf25b41672f.zip
  # renovate: datasource=custom.pio depName=rweather/Crypto packageName=rweather/library/Crypto
  rweather/Crypto@0.4.0

lib_ignore = 
  ${esp32_base.lib_ignore} NimBLE-Arduino libpax